//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureLiquid.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureLiquid.Tests.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;contentSource&quot;: &quot;ikano.sg/bc.14/availability&quot;,
        ///  &quot;data&quot;: {
        ///    &quot;bufferStock&quot;: -7,
        ///    &quot;businessUnitCode&quot;: &quot;001&quot;,
        ///    &quot;businessUnitType&quot;: &quot;STO&quot;,
        ///    &quot;id&quot;: &quot;lFWpkKiJju&quot;,
        ///    &quot;inTransit&quot;: 0,
        ///    &quot;itemType&quot;: &quot;ART&quot;,
        ///    &quot;lastModified&quot;: &quot;2022-10-04T08:17:44.7148833Z&quot;,
        ///    &quot;quantityReserved&quot;: 0,
        ///    &quot;sellableStock&quot;: 10000,
        ///    &quot;stockInPicking&quot;: 10007
        ///  },
        ///  &quot;dataSchema&quot;:
        ///    &quot;https://github.com/inter-ikea/cbf-ross-rpic-bc-inventoryexport/blob/main/Schemas/invexp.update.input.v1.schema.json&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventContent {
            get {
                return ResourceManager.GetString("EventContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;bufferStock&quot;: &quot;-7&quot;
        ///}.
        /// </summary>
        internal static string EventResult {
            get {
                return ResourceManager.GetString("EventResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;bufferStock&quot;: &quot;{{ content.data.bufferStock }}&quot;
        ///}.
        /// </summary>
        internal static string EventTemplate {
            get {
                return ResourceManager.GetString("EventTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    &lt;h1&gt;Simple Template&lt;/h1&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string SimpleResult {
            get {
                return ResourceManager.GetString("SimpleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    &lt;h1&gt;{{ content.Title }}&lt;/h1&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string SimpleTemplate {
            get {
                return ResourceManager.GetString("SimpleTemplate", resourceCulture);
            }
        }
    }
}
