name: "CD: Release and Publish"

on:
  push:
    # Run on changes and let release-please create PRs and publish releases
    # Bump package versions as needed and publish packages to NuGet gallery
    branches:
      - main
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"
      - ".github/workflows/cd_release_please.yml"
      - ".release-please-manifest.json"
      - "release-please-config.json"

jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "16"

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: lekman/release-please-dotnet@v1

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - run: |
          dotnet publish -c Release
          dotnet nuget push **/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate
