name: "CI: Unit Tests"

on:
  pull_request:
    branches: [main]
  push:
  workflow_dispatch:

jobs:
  unit:
    name: Unit Tests
    uses: ./.github/workflows/build_verification_dotnet.yml
    secrets: inherit
    with:
      project_path: .
      run_tests: true
